"""Database creation

Revision ID: b60be5ef7d74
Revises: 
Create Date: 2023-05-31 17:37:22.668173

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = 'b60be5ef7d74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=35), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__role')),
                    sa.UniqueConstraint('name', name=op.f('uq__role__name')),
                    schema='events'
                    )
    op.create_index(op.f('ix__role__id'), 'role', ['id'], unique=False, schema='events')
    op.create_table('user',
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['events.role.id'], name=op.f('fk__user__role_id__role')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__user')),
                    schema='events'
                    )
    op.create_index(op.f('ix__user__email'), 'user', ['email'], unique=True, schema='events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__user__email'), table_name='user', schema='events')
    op.drop_table('user', schema='events')
    op.drop_index(op.f('ix__role__id'), table_name='role', schema='events')
    op.drop_table('role', schema='events')
    # ### end Alembic commands ###
