"""Create Database

Revision ID: ca5f0ae50152
Revises: 
Create Date: 2023-06-17 17:27:49.115763

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = 'ca5f0ae50152'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('place', sa.String(length=100), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('max_players', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__event')),
    sa.UniqueConstraint('name', 'place', 'start_date', name='uq__event__name__place__date'),
    schema='events'
    )
    op.create_index(op.f('ix__event__id'), 'event', ['id'], unique=False, schema='events')
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__role')),
    sa.UniqueConstraint('name', name=op.f('uq__role__name')),
    schema='events'
    )
    op.create_index(op.f('ix__role__id'), 'role', ['id'], unique=False, schema='events')
    op.create_table('user',
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user')),
    schema='events'
    )
    op.create_index(op.f('ix__user__email'), 'user', ['email'], unique=True, schema='events')
    op.create_table('event_access_rights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event.id'], name=op.f('fk__event_access_rights__event_id__event')),
    sa.ForeignKeyConstraint(['role_id'], ['events.role.id'], name=op.f('fk__event_access_rights__role_id__role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__event_access_rights')),
    sa.UniqueConstraint('role_id', 'event_id', name='uq__event_id__role_id'),
    schema='events'
    )
    op.create_index(op.f('ix__event_access_rights__id'), 'event_access_rights', ['id'], unique=False, schema='events')
    op.create_table('user_privileges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['events.role.id'], name=op.f('fk__user_privileges__role_id__role')),
    sa.ForeignKeyConstraint(['user_id'], ['events.user.id'], name=op.f('fk__user_privileges__user_id__user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_privileges')),
    sa.UniqueConstraint('user_id', 'role_id', name='uq__user_id__role_id'),
    schema='events'
    )
    op.create_index(op.f('ix__user_privileges__id'), 'user_privileges', ['id'], unique=False, schema='events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__user_privileges__id'), table_name='user_privileges', schema='events')
    op.drop_table('user_privileges', schema='events')
    op.drop_index(op.f('ix__event_access_rights__id'), table_name='event_access_rights', schema='events')
    op.drop_table('event_access_rights', schema='events')
    op.drop_index(op.f('ix__user__email'), table_name='user', schema='events')
    op.drop_table('user', schema='events')
    op.drop_index(op.f('ix__role__id'), table_name='role', schema='events')
    op.drop_table('role', schema='events')
    op.drop_index(op.f('ix__event__id'), table_name='event', schema='events')
    op.drop_table('event', schema='events')
    # ### end Alembic commands ###
